name: Plugin Check

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - trunk
    pull_request:
        types:
            - opened
            - synchronize
            - ready_for_review

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    plugin-check:
        name: Run Plugin Check
        runs-on: 'ubuntu-24.04'
        permissions:
            contents: read
        timeout-minutes: 20
        steps:
            - name: Checkout repository
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Set up PHP
              uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2.35.4
              with:
                  php-version: '8.3'
                  coverage: none

            - name: Install Composer dependencies
              uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # v3.1.1

            - name: Setup Node
              uses: actions/setup-node@65d868f8d4d85d7d4abb7de0875cde3fcc8798f5 # v5.0.0
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - name: Install NPM dependencies
              run: npm ci

            - name: Build assets
              run: npm run build

            - name: Run plugin check
              uses: wordpress/plugin-check-action@ec9b3fe9beaa76bcc4510b7ba2cb5855a5f80f3f # v1.1.4
              with:
                  wp-version: 'latest'
                  # Exclude file_type because of the dev files present in the repository.
                  exclude-checks: |
                      file_type
                  exclude-directories: |
                      .github
                      docs
                      tests